server:
  port: 8000
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许请求来源（老版本叫allowedOrigin）
            allowedOriginPatterns: '*'
            # 是否允许携带cookie
            allowCredentials: true
            # 允许携带的头信息
            allowedHeaders: '*'
            # 允许的请求方式
            allowedMethods: '*'
            # 跨域检测的有效期, 会发起一个 OPTION 请求, 3600 秒, 即一个小时
            maxAge: 3600
      routes:
        # 路由转发，将/member/...的请求转发到member模块
        - id: member
          predicates:
            - Path=/member/**
          uri: http://127.0.0.1:8001

